<a href="https://colab.research.google.com/github/mukund-23/Pytorch-Tutorial/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch
import numpy as np
# Create random tensor
t = torch.rand(7,7)
t

tensor([[0.0910, 0.6531, 0.0734, 0.3746, 0.6577, 0.6994, 0.1221],
        [0.7291, 0.7486, 0.3047, 0.6410, 0.5919, 0.8245, 0.5951],
        [0.3431, 0.5819, 0.9766, 0.0430, 0.1686, 0.5155, 0.6091],
        [0.2707, 0.5197, 0.5408, 0.6820, 0.3981, 0.3094, 0.1184],
        [0.2755, 0.0061, 0.5039, 0.5628, 0.3421, 0.0808, 0.2539],
        [0.6956, 0.4665, 0.6047, 0.9078, 0.8076, 0.6119, 0.1877],
        [0.9009, 0.9509, 0.8219, 0.4683, 0.8439, 0.7738, 0.1737]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
t2 = torch.rand(1,7)
# Perform matrix multiplication
mat_mul = torch.matmul(t,t2.T)
mat_mul

tensor([[1.5963],
        [2.5780],
        [1.8131],
        [1.7247],
        [1.1128],
        [2.6093],
        [3.3042]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [9]:
# Set manual seed
MANUAL_SEED = 0
# Create two random tensors
torch.manual_seed(MANUAL_SEED)
t1 = torch.rand(7,7)
torch.manual_seed(MANUAL_SEED)
t2 = torch.rand(1,7)
# Matrix multiply tensors
res = torch.matmul(t1, t2.T)
res

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [10]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [11]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
(torch.cuda.is_available())
# Create two random tensors on GPU
t1_gpu = torch.rand(2,3).cuda()
t2_gpu = torch.rand(2,3).cuda()
t1_gpu, t2_gpu

(tensor([[0.8964, 0.4556, 0.6323],
         [0.3489, 0.4017, 0.0223]], device='cuda:0'),
 tensor([[0.1689, 0.2939, 0.5185],
         [0.6977, 0.8000, 0.1610]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [13]:
# Perform matmul on tensor_A and tensor_B
mat_mul_cuda = torch.matmul(t1_gpu, t2_gpu.T)
mat_mul_cuda

tensor([[0.6131, 1.0917],
        [0.1886, 0.5684]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [14]:
# Find max
print(t1_gpu.max(), t2_gpu.max())
# Find min
print(t1_gpu.min(), t2_gpu.min())

tensor(0.8964, device='cuda:0') tensor(0.8000, device='cuda:0')
tensor(0.0223, device='cuda:0') tensor(0.1610, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [16]:
# Find arg max
print(mat_mul_cuda.argmax())
# Find arg min
print(mat_mul_cuda.argmin())

tensor(1, device='cuda:0')
tensor(2, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [21]:
# Set seed
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)
# Create random tensor
rand_tensor = torch.rand(size = (1,1,1,10))

# Remove single dimensions
rand_tensor_squeezed = rand_tensor.squeeze()

# Print out tensors and their shapes
print(rand_tensor, rand_tensor.shape)
print(rand_tensor_squeezed, rand_tensor_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
